SUPABASE_URL = "https://ozjfvcfkhuajljlfdjio.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96amZ2Y2ZraHVhamxqbGZkamlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTQ0NzUsImV4cCI6MjA2NTc3MDQ3NX0.7QBEW-65dDzTWcKxvtCVg7tVfRCRorDWCWPDsamRy3E  "
